Can't run `k step` after `k run` with this error message

```
Temporary breakpoint 1, 0x00005555555f19d0 in main ()
Python Exception <class 'gdb.error'>: No source file named definition.kore.
Error occurred in Python: No source file named definition.kore.
```

I dont know how to proceed. Sorry :(
